# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lgE5rJgiL_LBJTyegG0K4RSmmClPOqqY
"""

pip install sentence-transformers scikit-learn pandas matplotlib

import pandas as pd
import matplotlib.pyplot as plt

from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

complaints = [
    "My car takes longer to start in the morning",
    "Battery voltage is low and vehicle cranks slowly",
    "The vehicle does not start immediately",

    "Engine warning light is displayed on dashboard",
    "Check engine light is blinking",
    "Engine alert appeared while driving",

    "Braking noise is coming from front wheels",
    "Brake pedal feels hard and noise is heard",
    "There is a squeaking sound while braking",

    "Fuel efficiency has reduced significantly",
    "Mileage has dropped after last service",
    "Vehicle is consuming more fuel than usual"
]

df = pd.DataFrame({
    "complaint": complaints
})

print(df)

from sentence_transformers import SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = model.encode(df["complaint"].tolist())

print(embeddings.shape)

kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

df["cluster"] = kmeans.fit_predict(embeddings)

print(df)

for k in range(2, 8):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(embeddings)
    print(k, labels)

cluster_names = {
    0: "Engine Warning Issues",
    1: "Brake Noise Issues",
    2: "Battery / Starting Issues",
    3: "Fuel Efficiency Issues"
}

df["cluster_name"] = df["cluster"].map(cluster_names)

print(df[["complaint", "cluster_name"]])

pca = PCA(n_components=2)
reduced_embeddings = pca.fit_transform(embeddings)

df["x"] = reduced_embeddings[:, 0]
df["y"] = reduced_embeddings[:, 1]

plt.figure(figsize=(8, 6))
plt.scatter(df["x"], df["y"], c=df["cluster"])

for i, row in df.iterrows():
    plt.text(row["x"], row["y"], str(i))

plt.title("Customer Complaint Clusters Using LLM Embeddings")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.show()